from __future__ import annotations

from contextlib import AbstractContextManager
from pathlib import Path
from types import TracebackType
from typing import Protocol, TYPE_CHECKING

from ..domain import Rect, Rotation
from ..temp_workspace import SourceWorkspace

if TYPE_CHECKING:
    from .com_document import TraversalBudget

Snapshot = dict[str, object]


class CadDocument(Protocol):
    def configure_extraction(self, enabled: bool) -> None: ...
    def for_scale_detection(self) -> CadDocument: ...
    def filtered_snapshots(self, types: tuple[str, ...], bounds: Rect | None = None) -> list[Snapshot]: ...
    def nested_text_snapshots(self, reference: Snapshot, max_blocks: int | None = None,
                              max_entities: int | None = None, *, budget: TraversalBudget | None = None) -> list[Snapshot]: ...
    def filtered_geometry_snapshots(self, bounds: Rect, max_blocks: int = 64,
                                    max_entities: int = 5000) -> list[Snapshot]: ...
    def is_known_noncontributing_text_insert(self, reference: Snapshot) -> bool: ...
    def is_noncontributing_text_insert(self, reference: Snapshot, *, budget: TraversalBudget) -> bool: ...
    def is_noncontributing_unsupported_insert(self, reference: Snapshot, *, budget: TraversalBudget) -> bool: ...
    def plot_pdf(self, output: Path, window: Rect, rotation: Rotation,
                 preferred_media_names: tuple[str, ...]) -> None: ...


class CadSession(Protocol):
    @property
    def is_usable(self) -> bool: ...
    @property
    def owned_pid(self) -> int | None: ...
    @property
    def reported_version(self) -> str | None: ...
    def __enter__(self) -> CadSession: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None,
                 tb: TracebackType | None) -> None: ...
    def working_document(self, workspace: SourceWorkspace) -> AbstractContextManager[CadDocument]: ...
